// ----------------------------------------------------------------------

const ROOTS = {
    AUTH: '/auth',
    ADMIN: '/admin',
    ECOM: '/manager',
    SYSYTEM_USER: '/system-user',
};

// ----------------------------------------------------------------------

export const paths = {
    // AUTH
    auth: {
        jwt: {
            login: `${ROOTS.AUTH}/login`,
            register: `${ROOTS.AUTH}/register`,
        },
        resetPassword: `/reset-password`,
        passwordSuccess: '/password-update-success',
        verifyEmail: '/verify-email',
        setPassword: `/set-password`,
    },
    // DASHBOARD
    dashboard: {
        home: '/dashboard',
        mobileRecharge: '/mobile-recharge',
        billPayments: '/bill-payments',
        corporateTravel: '/corporate-travel',
        payroll: '/payroll',
        payout: '/payouts',
        payoutAll: '/payouts/all-payouts',
        payoutBillPayout: '/payouts/bill-payout',
        payoutRent: '/payouts/rent',
        payoutVendorPayments: '/payouts/vendor-payments',
        officeSupplies: '/office-supplies',
        productDetails: '/office-supplies/product-details/:id',
        cartPage: '/office-supplies/carts',
        orderPlaced: '/office-supplies/order-placed',
        orderDetails: '/office-supplies/order-details',
        orderDetailsMobile: '/office-supplies/order-details-mobile/:id',
        cancelledDetails: '/office-supplies/cancelled-details',
        returnedDetails: '/office-supplies/returned-details',
        orderHistory: '/office-supples/order-history',
        changeAddress: '/office-supplies/change-address',
        subscriptions: '/softwares',
        logistics: '/logistics',
        giftCards: '/gift-cards',
        connect: '/marketplace',
        works: 'more-services/works',
        invoicing: '/invoicing',
        zeroCarbon: 'more-services/zero-carbon',
        tax: '/tax',
        moreServices: '/more-services',
        carLeasing: 'more-services/car-leasing',
        carRentals: 'more-services/car-rentals',
        comingSoon: '/more-services/coming-soon',
        reports: '/reports',
        needHelp: '/need-help',
        profile: '/profile',
        businessDocs: '/more-services/bussiness-docs',
        whatsappForBusiness: '/whatsApp-for-business',
        eSign: '/more-services/eSign',
        licenseRenewal: '/license-renewal',
        officeAddress: 'more-services/office-address',
        hotels: '/hotels',
        insurance: '/insurance',
        soundBox: '/sound-box',
        paytmBpos: '/paytm-bpos',
        vendorPayouts: 'vendor-payouts',
        corporateCard: 'corporate-card',
        paymentLinks: '/payment-links',
        payments: '/payments',
        notifications: '/notifications',
        pekoCredit: '/peko-credit',
        pekoCloud: '/hub',
        plans: '/plans',
        serviceNotAvailable: '/service-not-available',
        settings: '/settings',
        emailDomain: 'more-services/business-emails',
        pekoConnect: '/more-services/connect',
        hike: 'more-services/hike',
        turbo: '/turbo',
        pekoWallet: 'peko-wallet',
        verificationSuite: '/verification-suite',
        domainHosting: '/domain-&-hosting',
        procure: '/procure',
    },
    zeroCarbon: {
        id: '/:id',
        index: 'zero-carbon',
        carbonCalculator: 'carbon-calculator',
        result: 'result',
        projectDetails: 'project-details',
        neutralize: 'neutralize',
        buyCredits: 'buy-Credits',
        impactReport: 'impact-report',
        projectListing: 'project-listing',
        whyAct: 'why-act',
        transactions: 'transactions',
        payment: 'payment',
        paymentStatus: 'payment-status',
        shareImpact: 'share-impact',
    },
    connect: {
        index: 'marketplace',
        details: 'details/:id',
        success: 'success',
        failed: 'failed',
    },
    needHelp: {
        index: 'need-help',
        faq: 'frequently-asked-questions',
    },
    pekoConnect: {
        index: 'connect',
        videoCall: 'video-call',
    },
    reports: {
        index: 'reports',
        faq: 'faq',
        addOns: 'add-ons',
    },
    paymentLinks: {
        index: 'payment-links',
        CreatePayment: 'create',
        ENachMandates: 'enach-mandates',
        Transactions: 'transactions',
        TransactionDetail: 'transactions/transaction-details',
        VirtualAccountStatement: 'virtual-account-statement',
    },
    paymentLinkPublicSuccess: '/payment-link/success',
    eNachMandatePublicSuccess: '/enach-mandate/success',
    subscriptions: {
        index: 'softwares',
        id: '/:id',
        details: 'details',
        companyDetails: 'purchase',
        payment: 'payment',
        success: 'success',
        failed: 'failed',
        orderHistory: 'order-history',
    },
     softwares: {
        index: 'softwares',
        category: 'category',
        product: 'product',
        findSoftware: 'find-software',
        success: 'success',
        viewPlans: 'view-plans',
        orderHistory: 'order-history',
        managePlan: 'manage-plan',
        searchResults: 'search-results',
        getAssistanceSuccess: 'get-assistance-success',
    },
    businessDocs: {
        index: 'business-docs',
        category: 'category',
    },
    telecomPayments: {
        index: 'mobile-recharge',
        prepaid: 'prepaid',
        postpaid: 'postpaid',
        test: 'test',
    },
    billPayments: {
        index: 'bill-payments',
        electricity: 'electricity-bill',
        broadband: 'broadband-bill',
        lpg: 'lpg-cylinder',
        water: 'water-bill',
        landline: 'landline-bill',
        pipedGas: 'piped-gas',
        education: 'education-fee',
        bulkUpload: 'bulkupload',
        bulkPayment: 'bulk-payment',
        creditCard: 'credit-card',
        cable: 'cable-recharge',
        dth: 'dth-recharge',
        fastag: 'fastag-recharge',
        loanRepayment: 'loan-repayment',
        municipalTaxes: 'municipal-taxes',
        municipalServices: 'municipal-services',
        recurringDeposite: 'recurring-deposite',
        rental: 'rental',
        donations: 'donations',
        Insurance: 'insurance',
        bikeInsurance: 'bike-insurance',
        carInsurance: 'car-insurance',
        lifeInsurance: 'life-insurance',
        clubs: 'clubs-associations',
        hospital: 'hospital-pathology',
        housingSociety: 'housing-society',
        subscription: 'subscription',
        ncmc: 'ncmc',
        nps: 'nps',
        prepaidMeter: 'prepaid-meter',
        complaintRegistration: 'complaint-registration',
        ComplaintRegister: 'register-complaint',
        success: 'success',
    },
    payments: {
        index: 'payments',
        paymentsuccess: 'payment-success',
        paymentFailure: 'payment-failure',
        paymentPending: 'payment-pending',
    },
    hotels: {
        index: 'hotels',
        details: 'hotel-listing',
        hotelView: 'hotel-details',
        bookings: 'booking-summary',
        manageBookings: 'manage-bookings',
        userDetails: 'guest-information',
        reviewPayment: 'payment-review',
    },
    officeSupplies: {
        index: 'office-supplies',
        id: 'id',
        productDetails: 'product-details',
        cartPage: 'cart',
        orderPlaced: 'order-placed',
        orderDetails: 'order-details',
        orderHistory: 'order-history',
    },
    airline: {
        index: 'airline',
        results: 'flight-details',
        details: 'passenger-details',
        summary: 'summary',
        manage: 'manage-bookings',
        bookingDetails: 'modify-or-cancel-booking',
        cancelDetails: 'cancel',
        cancelSuccess: 'cancellation-received',
    },
    logistics: {
        index: 'logistics',
        details: 'shipment-details',
        payment: 'payment',
        paymentStatus: 'payment-status',
        track: 'track',
        trackOrderDetails: 'track-order-details',
        orderHistory: 'order-history',
        orderDetails: 'order-view',
        returnShipment: 'return-shipment',
    },
    // logistics: {
    //     index: 'logistics',
    //     details: 'shipment-details',
    //     payment: 'payment',
    //     paymentStatus: 'payment-status',
    //     track: 'track',
    //     orderHistory: 'order-history',
    //     orderDetails: 'order-view',
    // },
    esim: {
        index: 'eSIM',
        packages: 'packages',
        details: 'package-details',
        orders: 'orders',
        esimDetails: 'package-details',
        ReplacePackage: 'replace-package',
        topup: 'top-up-package-details',
        howEsim: 'how-it-works',
    },
    eSign: {
        index: 'eSign',
        uploadPage: 'upload',
        viewPage: 'view',
        historyPage: 'status',
        successPage: 'success',
        settings: 'settings',
    },
    officeAddress: {
        index: 'office-address',
        plans: 'plans',
        basic: 'basic',
        premium: 'premium',
        flexi: 'flexi',
        orderhistory: 'order-history',
    },
    hike: {
        index: 'hike',
        purchasePage: 'purchase-hike',
        checkoutPage: 'purchase-details',
        historyPage: 'history',
        successPage: 'success',
    },
    works: {
        index: 'works',
        detail: 'details',
        id: ':id',
        purchased: 'purchased',
        purchase: 'purchase',
        planId: ':planId',
        orderHistory: 'order-history',
        orderDetails: 'order-details',
    },
    officeAddresses: {
        details: 'details',
        basic: 'basic',
        premium: 'premium',
        flexi: 'flexi',
    },
    whatsappForBusiness: {
        index: 'whatsApp-for-business',
        planDetails: 'plan-details',
        MyProjects: 'my-projects',
        reviewOrder: 'subscription',
        paymentsuccess: 'payment-success',
        successPage: 'success',
    },
    emailDomain: {
        index: 'business-emails',
        detailsPage: ':detail',
        historyPage: 'order-history',
    },
    soundbox: {
        orderDetails: 'order-details',
        details: 'details',
    },
    paytmBpos: {
        index: 'paytm-bpos',
        request: 'request',
        submitted: 'request-submitted',
        orderHistory: 'order-history',
    },
    payment: {
        success: 'success',
        failed: 'failed',
    },
    invoice: {
        index: 'invoicing',
        kyb: 'kyb',
        kybDocumentPage: 'documents',
        kybVerification: 'kyb-verification',
        kybeSign: 'eSign',
        upload: 'upload-invoice',
        create: 'create-invoice',
        edit: 'edit-invoice/:id',
        customers: 'customers',
        invoicedetails: 'invoice-details/:id',
        invoicehistory: 'track-invoice',
        trackDetails: 'invoice-history-details',
        guidelines: 'guidelines',
        success: 'success',
        paymentLinks: 'payment-links',
        orderHistory: 'order-history',
        allInvoice: 'all-invoices',
    },
    giftcards: {
        index: 'gift-cards',
        details: 'details',
        id: '/:id',
        orderHistory: 'order-history',
        checkout: 'checkout',
        success: 'success',
        failure: 'failure',
    },
    settings: {
        index: 'settings',
    },
    payroll: {
        index: 'payroll',
        announcements: 'announcements',
        id: '/:id',
        eId: '/:eId',
        salaryProfile: 'salary-profile',
        addEmployee: 'add-employee',
        employeesSalary: 'employees-salary',
        employeeProfile: 'employee-profile',
        employees: 'employees',
        payrollSettings: 'HR-settings',
        leaveConfig: 'leave-configuration',
        complianceSettings: 'compliance-settings',
        activityCalendar: 'activity-calendar',
        bulkUpload: 'bulk-upload',
        employeeLeave: 'employee-Leaves',
        wpsRegistration: 'wps-registration',
        employeeSuccess: 'success',
        employeeAdded: 'employee-added',
        employeeReimbursement: 'employee-reimbursements',
        reports: 'reports',
        allDocuments: 'all-documents',
        documentsDetails: 'documents-details',
        leaveSummary: 'leave-summary/:id',
        employeeSalaryProfile: 'employee-salary-profile',
        payrollRecordSuccess: 'payroll-record-success',
    },
    pekoCloud: {
        index: 'hub',
        settings: 'settings',
        taskToDo: 'task-to-do',
        companyDocuments: 'company-documents',
        ownershipDocuments: 'ownership-documents',
        financials: 'financials',
        employeeDetails: 'employee-details',
        subscriptions: 'subscriptions',
        assets: 'assets',
        assetsDetails: 'assets-details',
        fleet: 'fleet',
        fleetDetails: 'fleet-details',
        chequeBookDetails: 'cheque-book-details',
        chequeDetails: 'cheque-details',
    },
    pekoCredits: {
        index: 'peko-credit',
    },
    turbo: {
        index: 'turbo',
        addVehicle: 'add-vehicle',
        viewDetails: 'view-vehicle-details',
        driverProfiles: 'driver-profiles',
        addDriver: 'add-driver',
        driverDetails: 'view-driver-details',
        documentCentre: 'document-center',
        manageSubscription: 'manage-subscription',
        manageFleet: 'manage-fleet',
        operationLog: 'operations-log',
    },
    plans: {
        index: 'plans',
        reviewOrder: 'review-order',
        paymentsuccess: 'payment-success',
        paymentFailure: 'payment-failure',
    },
    pekoWallet: {
        index: 'peko-wallet',
        paymentsuccess: 'topup-success',
        transactionHistory: 'wallet-history',
        paymentFailure: 'payment-failure',
    },
    profile: {
        index: 'profile',
        kyb: 'One-KYB',
    },
    verificationSuite: {
        index: 'verification-suite',
        verificationHistory: 'verification-history',
        verificationDetails: 'verification-details',
    },
    domainHosting: {
        index: 'domain-&-hosting',
        cart: 'cart',
        checkout: 'checkout',
        vpsServer: 'vps-server',
        sharedHosting: 'shared-hosting',
        googleWorkspace: 'google-workspace',
        googleWorkspaceOrder: 'google-workspace/order-processing',
        titanEmail: 'titan-email',
        titanEmailOrder: 'titan-email/order-processing',
        domainAssign: 'domain-assign',
        manageSubscription: 'manage-subscription',
    },
    procure: {
        index: 'procure',
        purchaseRequests: {
            index: 'purchase-requests',
            create: 'create',
            view: ':id',
        },
        rfq: {
            index: 'rfq',
            create: 'create',
            view: ':id',
        },
        proposals:{
            index: 'proposals',
            view: ':proposalId',
            compare: 'compare/:rfqId',
        },        
        purchaseOrders: {
            index: 'purchase-orders',
            view:  ':poId',
            create: 'create',
        },
        invoicing: {
            index: 'invoicing',
            view:  ':invoiceId',
        },
        vendor: {
            index: 'vendor',
            create: 'create',
        },
    },

    // ----ADMIN ROUTES----
    manage: {
        index: `${ROOTS.ADMIN}/manage`,
        bulk: 'bulk',
        softwareProducts: 'software-products',
        softwarePlans: 'software-plans',
        officeAddress: 'office-address',
        workspaces: 'workspaces',
        corporateTaxRegistration: 'corporate-tax-registration',
        pekoWorks: 'peko-works',
        workPlans: 'work-plans',
        giftCards: 'gift-cards',
        connect: 'connect',
        eDocs: 'business-docs',
        attestationCategory: 'attestation',
        vendorPayouts: 'vendor-payout',
        bussinessEmails: 'business-emails',
        bussinessEmailsplans: 'business-emails-plans',
        domainHostingPlans: 'domain-&-hosting-plans',
        domainHostingCancellations: 'domain-&-hosting-cancellations',
        hike: 'hike',
        esimPlans: 'esim-plans',
        invoiceKyb: 'invoice-kyb',
        collectorKyb: 'collector-kyb',
        walletDenomination: 'peko-wallet',
        // office-supplies
        returnRequest: 'return-request',
        cancelAndRefunds: 'cancel-&-refunds',
        orders: 'orders',
        products: 'products',
        bulkUpload: 'bulk-upload',
        // announcements
        notifications: 'notifications',
        // payment links
        paymentLinks: 'payment-links',
        kybVerifications: 'kyb-verifications',
        paymentMethods: 'payment-methods',
        // Payroll
        companyDocuments: 'company-documents',
        // Bill Payments
        billPayments: 'bill-payments',
    },
    users: {
        index: `${ROOTS.ADMIN}/users`,
        corporateUser: 'corporate-users',
        systemUser: 'system-users',
        roles: 'roles',
        // settings -> users
        PartnerRoles: 'Partner-Permissions',
        Partners: 'partners',
    },
    accounts: {
        index: `${ROOTS.ADMIN}/accounts`,
        selfTransfer: 'self-transfer',
        transferFunds: 'transfer-funds',
        createTransactions: 'create-transaction',
        bulkRefund: 'bulk-refund',
        refundTransactions: 'refund-transactions',
    },
    settingsAdmin: {
        index: `${ROOTS.ADMIN}/settings`,
        vendor: 'vendors',
        serviceOperators: 'service-operators',
        PackagePage: 'packages',
        Cashback: 'cashback',
        SubscriptionCodes: 'subscription-codes',
        DisabledService: 'disable-services',
        Banners: 'banners',
        Categories: 'categories',
        RefferalCode: 'referral-code',
        Templates: 'invoice-templates',
        AccessCode: 'access-code',
        CouponCode: 'coupon-code',
        WhatsAppNumbers: 'peko-whatsapp-numbers',
        Branding: 'branding',
        IPWhitelist: 'ip-whitelist',
        subscriptionReminders: 'subscription-reminders',
        servicePackages: 'service-packages',
        serviceRule: 'service-rule',
        pekoCredits: 'peko-credits',
    },
    needHelpAdmin: {
        tickets: 'tickets',
    },
    systemConfiguration: {
        passwordPolicy: 'password-policy',
        passwordProtection: 'password-protection',
        applicationPolicy: 'application-policy',
    },
    reportsAdmin: {
        SubscriptionsTable: 'subscriptions',
        Vendors: 'vendors',
        Corporate: 'corporate',
        Orders: 'orders',
        SoftwareOrders: 'software-orders',
        Esim: 'esim',
        OrderContent: 'peko-works',
        ConnectionRequests: 'connection-requests',
        Workspace: 'workspace-orders',
        Invoices: 'invoices',
        Attestation: 'attestations',
        Transactions: 'transactions',
        Esign: 'eSign',
        Airline: 'airline-cancellation',
        HotelCancellation: 'hotel-cancellation',
        HotelBookings: 'hotel-bookings',
         AirlineBookings: 'airline-bookings',
        AirlineModification: {
            index: 'airline-modification',
            modificationRequest: 'request',
        },
        ReportScheduling: 'scheduling-reports',
        PaymentLinks: 'payment-links',
        BusinessEmails: 'business-emails',
        TransactionsReport: 'transaction-report',
        VerificationReports: 'verification-reports',
        // accounts -> reports
        walletReport: 'wallet-reports',
        // users -> reports
        pendingSignups: 'pending-sign-ups',
        // domain & hosting
        DomainHostingRefunds: 'domain-&-hosting-refunds',
    },
    admin: {
        index: `${ROOTS.ADMIN}`,
        dashboard: `${ROOTS.ADMIN}/dashboard`,
        users: `${ROOTS.ADMIN}/users`,
        accounts: `${ROOTS.ADMIN}/accounts`,
        reports: `${ROOTS.ADMIN}/reports`,
        officeSupplies: `${ROOTS.ADMIN}/office-supplies`,
        support: `${ROOTS.ADMIN}/support`,
        manage: `${ROOTS.ADMIN}/manage`,
        bulkUpload: `${ROOTS.ADMIN}/bulk-upload`,
        settings: `${ROOTS.ADMIN}/settings`,
        needHelp: `${ROOTS.ADMIN}/need-help`,
        announcement: `${ROOTS.ADMIN}/announcement`,
    } as Record<string, string>,
    ecomManager: {
        index: `${ROOTS.ECOM}`,
        dashboard: `${ROOTS.ECOM}/dashboard`,
        orders: `${ROOTS.ECOM}orders`,
        needHelp: `${ROOTS.ECOM}/need-help`,
        officeSupplies: `${ROOTS.ECOM}/officeSupplies`,
        returnAndRefunds: `${ROOTS.ECOM}/returnAndRefunds`,
        cancelAndRefunds: `${ROOTS.ECOM}/cancelAndRefunds`,
        vendors: `${ROOTS.ECOM}/vendors`,
        categories: `${ROOTS.ECOM}/categories`,
        products: `${ROOTS.ECOM}/products`,
    } as Record<string, string>,
    systemUser: {
        profile: `${ROOTS.SYSYTEM_USER}/profile`,
        index: `${ROOTS.SYSYTEM_USER}`,
        dashboard: `${ROOTS.SYSYTEM_USER}/dashboard`,
        users: `${ROOTS.SYSYTEM_USER}/users`,
        payrollConfig: `${ROOTS.SYSYTEM_USER}/payroll`,
        accounts: `${ROOTS.SYSYTEM_USER}/accounts`,
        reports: `${ROOTS.SYSYTEM_USER}/reports`,
        officeSupplies: `${ROOTS.SYSYTEM_USER}/office-supplies`,
        support: `${ROOTS.SYSYTEM_USER}/support`,
        manage: `${ROOTS.SYSYTEM_USER}/manage`,
        systemConfiguration: `${ROOTS.SYSYTEM_USER}/system-configuration`,
        bulkUpload: `${ROOTS.SYSYTEM_USER}/bulk-upload`,
        settings: `${ROOTS.SYSYTEM_USER}/settings`,
        needHelp: `${ROOTS.SYSYTEM_USER}/need-help`,
        announcement: `${ROOTS.SYSYTEM_USER}/announcements`,
    } as Record<string, string>,
};
